// @ts-nocheck — GENERATED by scripts/embed-migrations.ts — DO NOT EDIT.
// Embeds this package's Drizzle migrations into the compiled binary. Each *.sql is
// pulled in with `type: "text"` and the journal with `type: "json"` — Bun resolves
// both at BUILD time and compiles the contents in, so the binary carries its SQL
// with no drizzle/ folder on disk (see BUN_DATABASE.md). The SQL stays in
// drizzle/*.sql as the single source; regenerate with `bun run gen:migrations`.
//
// @ts-nocheck: these relative arbitrary-extension imports are resolved by Bun's
// bundler, not tsc — under `moduleResolution: "bundler"` an ambient
// `declare module "*.sql"` does not apply to RELATIVE specifiers. The exports
// below are still consumed with full type-checking (structurally, as
// EmbeddedMigrations) at their call sites.

import journalJson from "../drizzle/meta/_journal.json" with { type: "json" };
import m_0000_small_maximus from "../drizzle/0000_small_maximus.sql" with { type: "text" };
import m_0001_bored_harpoon from "../drizzle/0001_bored_harpoon.sql" with { type: "text" };
import m_0002_needy_red_ghost from "../drizzle/0002_needy_red_ghost.sql" with { type: "text" };
import m_0003_foamy_surge from "../drizzle/0003_foamy_surge.sql" with { type: "text" };
import m_0004_useful_exiles from "../drizzle/0004_useful_exiles.sql" with { type: "text" };
import m_0005_tag_post_count_trigger from "../drizzle/0005_tag_post_count_trigger.sql" with { type: "text" };
import m_0006_view_visitor_counts from "../drizzle/0006_view_visitor_counts.sql" with { type: "text" };
import m_0007_auth_sessions from "../drizzle/0007_auth_sessions.sql" with { type: "text" };
import m_0008_canonical_username_unique from "../drizzle/0008_canonical_username_unique.sql" with { type: "text" };
import m_0009_settings_and_api_keys from "../drizzle/0009_settings_and_api_keys.sql" with { type: "text" };
import m_0010_plugin_states from "../drizzle/0010_plugin_states.sql" with { type: "text" };
import m_0011_foamy_king_bedlam from "../drizzle/0011_foamy_king_bedlam.sql" with { type: "text" };
import m_0012_reflective_harrier from "../drizzle/0012_reflective_harrier.sql" with { type: "text" };
import m_0013_magical_sabra from "../drizzle/0013_magical_sabra.sql" with { type: "text" };
import m_0014_redundant_black_queen from "../drizzle/0014_redundant_black_queen.sql" with { type: "text" };

/** tag+".sql" → raw SQL text (compiled into the binary). */
const files: Record<string, string> = {
  "0000_small_maximus.sql": m_0000_small_maximus,
  "0001_bored_harpoon.sql": m_0001_bored_harpoon,
  "0002_needy_red_ghost.sql": m_0002_needy_red_ghost,
  "0003_foamy_surge.sql": m_0003_foamy_surge,
  "0004_useful_exiles.sql": m_0004_useful_exiles,
  "0005_tag_post_count_trigger.sql": m_0005_tag_post_count_trigger,
  "0006_view_visitor_counts.sql": m_0006_view_visitor_counts,
  "0007_auth_sessions.sql": m_0007_auth_sessions,
  "0008_canonical_username_unique.sql": m_0008_canonical_username_unique,
  "0009_settings_and_api_keys.sql": m_0009_settings_and_api_keys,
  "0010_plugin_states.sql": m_0010_plugin_states,
  "0011_foamy_king_bedlam.sql": m_0011_foamy_king_bedlam,
  "0012_reflective_harrier.sql": m_0012_reflective_harrier,
  "0013_magical_sabra.sql": m_0013_magical_sabra,
  "0014_redundant_black_queen.sql": m_0014_redundant_black_queen,
};

/** The embedded journal + SQL for this package, for `applyEmbeddedMigrations`. */
export const embeddedMigrations = {
  journal: JSON.stringify(journalJson),
  files,
};

/** How many migrations were compiled in (0 ⇒ a packaging fault; boot must fail). */
export const embeddedMigrationCount: number = Object.keys(files).length;
