// @ts-nocheck GENERATED by scripts/embed-migrations.ts — DO NOT EDIT.
// Embeds this package's Drizzle migrations into the compiled binary. Each *.sql is
// pulled in with `type: "text"` and the journal with `type: "json"` — Bun resolves
// both at BUILD time and compiles the contents in, so the binary carries its SQL
// with no drizzle/ folder on disk (see BUN_DATABASE.md). The SQL stays in
// drizzle/*.sql as the single source; regenerate with `bun run gen:migrations`.
//
// @ts-nocheck is required: these are RELATIVE arbitrary-extension imports, which
// tsc cannot resolve under `moduleResolution: "bundler"` — an ambient
// `declare module "*.sql"` only applies to BARE specifiers, not relative ones
// (verified: without it, every *.sql import errors TS2307). Bun's bundler resolves
// them; the exports below are still type-checked (as EmbeddedMigrations) at every
// call site, so the public surface stays safe.

import journalJson from "../drizzle/meta/_journal.json" with { type: "json" };
import m_0000_lying_tomas from "../drizzle/0000_lying_tomas.sql" with { type: "text" };
import m_0001_whole_shotgun from "../drizzle/0001_whole_shotgun.sql" with { type: "text" };
import m_0002_next_steel_serpent from "../drizzle/0002_next_steel_serpent.sql" with { type: "text" };

/** tag+".sql" → raw SQL text (compiled into the binary). */
const files: Record<string, string> = {
  "0000_lying_tomas.sql": m_0000_lying_tomas,
  "0001_whole_shotgun.sql": m_0001_whole_shotgun,
  "0002_next_steel_serpent.sql": m_0002_next_steel_serpent,
};

/** The embedded journal + SQL for this package, for `applyEmbeddedMigrations`. */
export const embeddedMigrations = {
  journal: JSON.stringify(journalJson),
  files,
};

/** How many migrations were compiled in (0 ⇒ a packaging fault; boot must fail). */
export const embeddedMigrationCount: number = Object.keys(files).length;
