import { fileURLToPath } from "node:url";

import { desc } from "drizzle-orm";
import { Elysia, t } from "elysia";

import {
  AuthenticationError,
  definePlugin,
  pluginRoutePrefix,
  type PluginContext,
} from "@bunbooru/plugin-sdk";

import { examplePings } from "./schema";

/** This plugin's stable id — also its route-prefix segment + migrations suffix. */
const PLUGIN_ID = "example";

/**
 * Build the example plugin's HTTP routes over the injected {@link PluginContext}.
 *
 * Extracted (rather than inlined in `register`) so its return TYPE can be
 * exported for a typed Eden client on the web — see {@link ExamplePluginApp}.
 * The `pluginRoutePrefix` prefix makes every path resolve under
 * `/api/v1/plugins/example`, matching how the host mounts it.
 *
 * Exercises the whole plugin surface: a Core service (`ctx.services.stats`), a
 * plugin-owned table (`ctx.db` + {@link examplePings}), and request auth
 * (`ctx.auth`) gating a write.
 */
export function buildExampleRoutes(ctx: PluginContext) {
  return new Elysia({ prefix: pluginRoutePrefix(PLUGIN_ID) })
    // Proves Core-service access: reports the live post count.
    .get("/ping", async () => {
      const { posts } = await ctx.services.stats.getStats();
      return { pong: true as const, posts };
    })
    // Proves plugin-owned table reads: the most recent pings.
    .get("/pings", async () => {
      const rows = await ctx.db
        .select()
        .from(examplePings)
        .orderBy(desc(examplePings.id))
        .limit(20);
      return rows.map((row) => ({
        id: row.id,
        note: row.note,
        createdAt: row.createdAt.toISOString(),
      }));
    })
    // Proves request auth + plugin-owned table writes: any signed-in user may
    // record a ping (401 when anonymous, via the shared error mapping).
    .post(
      "/pings",
      async ({ body, request }) => {
        const user = await ctx.auth.currentUser(request);
        if (!user) throw new AuthenticationError();
        const [row] = await ctx.db
          .insert(examplePings)
          .values({ note: body.note })
          .returning();
        if (!row) throw new Error("Failed to record ping");
        return { id: row.id };
      },
      { body: t.Object({ note: t.String({ minLength: 1, maxLength: 200 }) }) },
    );
}

/** Server type for a typed Eden Treaty client on the web (paths incl. the prefix). */
export type ExamplePluginApp = ReturnType<typeof buildExampleRoutes>;

/**
 * Example feature module — the reference plugin that exercises the SDK end to
 * end: plugin-owned migrations, Core-service access, a scoped `ctx.db`, request
 * auth, HTTP routes, and an admin page. It is the template the shimmie2 importer
 * (and future plugins) are built from.
 */
export const plugin = definePlugin({
  id: PLUGIN_ID,
  name: "Example",
  version: "0.1.0",
  migrations: {
    // Sibling `drizzle/` folder (generated by `bun run --cwd plugins/example db:generate`).
    // `fileURLToPath` (not `.pathname`) so an encoded char in the repo path (e.g.
    // a space → `%20`) or a Windows drive path resolves to a real filesystem path.
    migrationsFolder: fileURLToPath(new URL("../drizzle", import.meta.url)),
    migrationsTable: "__drizzle_migrations_example",
  },
  register(ctx) {
    return {
      routes: buildExampleRoutes(ctx),
      adminPages: [{ id: "pings", title: "Example: Pings" }],
    };
  },
});
