// @ts-nocheck — GENERATED by scripts/embed-migrations.ts — DO NOT EDIT.
// Embeds this package's Drizzle migrations into the compiled binary. Each *.sql is
// pulled in with `type: "text"` and the journal with `type: "json"` — Bun resolves
// both at BUILD time and compiles the contents in, so the binary carries its SQL
// with no drizzle/ folder on disk (see BUN_DATABASE.md). The SQL stays in
// drizzle/*.sql as the single source; regenerate with `bun run gen:migrations`.
//
// @ts-nocheck: these relative arbitrary-extension imports are resolved by Bun's
// bundler, not tsc — under `moduleResolution: "bundler"` an ambient
// `declare module "*.sql"` does not apply to RELATIVE specifiers. The exports
// below are still consumed with full type-checking (structurally, as
// EmbeddedMigrations) at their call sites.

import journalJson from "../drizzle/meta/_journal.json" with { type: "json" };
import m_0000_eminent_bullseye from "../drizzle/0000_eminent_bullseye.sql" with { type: "text" };

/** tag+".sql" → raw SQL text (compiled into the binary). */
const files: Record<string, string> = {
  "0000_eminent_bullseye.sql": m_0000_eminent_bullseye,
};

/** The embedded journal + SQL for this package, for `applyEmbeddedMigrations`. */
export const embeddedMigrations = {
  journal: JSON.stringify(journalJson),
  files,
};

/** How many migrations were compiled in (0 ⇒ a packaging fault; boot must fail). */
export const embeddedMigrationCount: number = Object.keys(files).length;
